      - name: Check & Fix Content
        run: |
          echo "🔍 Starte Rechtschreibprüfung & Auto-Fix..."
          node scripts/fixContent.js || echo "Keine Änderungen gefunden"

          # Git-Config für Actions-Bot
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Änderungen committen
          git add content || echo "Nichts zu committen"
          git commit -m "🔍 Auto-Check: Content korrigiert" || echo "Keine Änderungen gefunden"

          # Neu: Pull & Push mit Rebase -> verhindert Konflikte beim Push
          git pull --rebase origin main
          git push || echo "Kein Push notwendig"
