name: 🚀 Deploy Blog to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 🧩 Automatische Reparatur aller Markdown-Dateien (Frontmatter, Slugs, Striche etc.)
      - name: Fix Markdown Articles
        run: node scripts/fixArticles.js

      # 🧠 Optional: Content-Check (Rechtschreibung, Struktur)
      - name: Check Content
        run: node scripts/fixContent.js

      # 🌐 Sitemap vor dem Deploy generieren
      - name: Generate Sitemap
        run: node scripts/generate-sitemap.js

      # 🏗️ Build und Export der statischen Seite
      - name: Build and Export
        run: npm run build && npm run export

      # 🚀 Deploy zu Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}
