name: 🚀 Deploy Blog to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v3

      - name: 🧠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  - name: 🧰 Install dependencies
  run: npm install

      - name: 🧹 Fix Markdown content
        run: npm run fix-content || true

      - name: 🧾 Fix Articles
        run: npm run fix-articles || true

      - name: 🔤 Fix Umlaute & Slugs
        run: npm run fix-umlaute || true && npm run fix-slugs || true

      - name: 🗺️ Generate Sitemap
        run: npm run generate-sitemap || true

      - name: ✅ Build Project
        run: npm run build

      - name: 🚀 Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
