name: Build and Deploy FinanzFreedom

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

- name: Install dependencies
  run: npm install

      # ✨ Neuer Schritt – generiert die Artikel vor dem Build
      - name: Fix content before build
        run: node scripts/fixContent.js

      - name: Build project
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
