name: 🚀 Deploy Blog to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: |
          npm ci || npm install

      - name: 🧹 Clear Build Cache
        run: |
          echo "🧹 Leere alte Build-Dateien..."
          rm -rf .next || true
          rm -rf node_modules/.cache || true

      - name: ✏️ Check & Fix Content
        run: |
          echo "✏️ Starte Rechtschreibprüfung & Auto-Fix..."
          npm run fix-content || echo "Keine Änderungen gefunden"

      - name: 🗺️ Generate Sitemap (before deploy)
        run: |
          echo "🗺️ Generiere Sitemap im XML-Format..."
          node scripts/generate-sitemap.js
          echo "✅ Sitemap wurde erzeugt."

      - name: 🚀 Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
        run: |
          echo "🚀 Starte Deployment zu Vercel..."
          npx vercel --prod --token=$VERCEL_TOKEN --scope=$VERCEL_SCOPE > deployment.txt

      - name: 🌍 Show Live URL
        run: |
          DEPLOY_URL=$(grep -o 'https://[^ ]*\.vercel\.app' deployment.txt | tail -n1)
          echo "✅ Live: $DEPLOY_URL"
