name: 🚀 Deploy Blog to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧩 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      # >>> Hier läuft dein automatischer Fix <<<
      - name: 🧹 Fix Markdown articles
        run: npm run fix-articles

      - name: 🔍 Check Content
        run: npm run fix-content

      - name: 🧠 Fix Umlaute & Slugs
        run: |
          npm run fix-umlaute
          node scripts/fixSlugs.js

      - name: 🏗️ Build Next.js project
        run: npm run build

      - name: 📤 Export static site
        run: npm run export

      - name: 🚀 Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
