name: Check Articles

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Check Article Structure
        run: node checkContent.js
      - name: Rechtschreibprüfung
        run: npx cspell "content/**/*.md"
