      - name: Deploy to Vercel
        run: |
          npx vercel --prod --yes \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope=${{ secrets.VERCEL_SCOPE }} \
            -A vercel.json
