name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci || npm install

      - name: Deploy to Vercel (prod)
        shell: bash
        run: |
          npx vercel --prod --yes -A vercel.json \
            --token="${{ secrets.VERCEL_TOKEN }}" \
            --scope="${{ secrets.VERCEL_SCOPE }}" > deployment.txt
          echo "url=$(grep -o 'https://[^ ]*vercel.app' deployment.txt | tail -n1)" >> "$GITHUB_ENV"

      - name: Show Deployment URL
        run: echo "🚀 Live: ${{ env.url }}"
